on: [push, pull_request_review]
jobs:
  packaging-actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: leafo/gh-actions-lua@v8.0.0
        with:
          luaVersion: "5.3.3"
      - run: cd /home/runner/work/Emmy-love-api/Emmy-love-api
      - run: mkdir api/love -p
      - run: lua checkAPIformat.lua
      - run: lua genEmmyAPI.lua
      - uses: actions/upload-artifact@v2
        with:
          name: api
          path: /home/runner/work/Emmy-love-api/Emmy-love-api/api